import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Heading, Screen } from '@/components/job-hunt-ui';
import { theme } from '@/constants/theme';
import { ActivityType, activityIcon, activityLabel } from '@/data/mock-data';
import { useJobHunt } from '@/data/job-hunt-store';

const types: ActivityType[] = ['application', 'interview', 'networking', 'skill_practice', 'search_session'];
export default function AddActivityScreen() {
  const { addActivity } = useJobHunt();
  const [type, setType] = useState<ActivityType>('interview');
  const [company, setCompany] = useState(''); const [role, setRole] = useState('');
  const [notes, setNotes] = useState(''); const [duration, setDuration] = useState('');
  const [stage, setStage] = useState('Phone screen'); const [outcome, setOutcome] = useState('Great');
  const [share, setShare] = useState(true);
  const save = () => { if (!company.trim() || !role.trim()) return; addActivity({ type, company, role, notes: notes || `${activityLabel[type]} logged`, visibility: share ? 'friends' : 'private', duration_minutes: duration ? Number(duration) : undefined, stage: type === 'interview' ? stage : undefined, outcome: type === 'interview' ? outcome : undefined }); router.replace('/'); };
  return <Screen><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Heading eyebrow="Keep the streak alive" title="Log activity" action="×" /><Text style={styles.question}>What did you move forward?</Text><View style={styles.typeGrid}>{types.map((item) => <Pressable key={item} onPress={() => setType(item)} style={[styles.typeOption, type === item && styles.typeOptionActive]}><Text style={[styles.typeIcon, type === item && styles.typeTextActive]}>{activityIcon[item]}</Text><Text style={[styles.typeText, type === item && styles.typeTextActive]}>{activityLabel[item]}</Text></Pressable>)}</View><View style={styles.form}><View style={styles.formHeading}><Text style={styles.formTitle}>{activityLabel[type]} details</Text><Text style={styles.saved}>Autosaved</Text></View><Field label="Role" value={role} onChangeText={setRole} placeholder="e.g. Product Designer" /><Field label="Company" value={company} onChangeText={setCompany} placeholder="e.g. Linear" /><View style={styles.twoFields}><View style={{ flex: 1 }}><Field label="Date" value="Today" editable={false} /></View><View style={{ flex: 1 }}><Field label="Duration" value={duration} onChangeText={setDuration} placeholder="Minutes" keyboardType="numeric" /></View></View>{type === 'interview' ? <InterviewDetails stage={stage} setStage={setStage} outcome={outcome} setOutcome={setOutcome} /> : null}<Text style={styles.label}>NOTES</Text><TextInput value={notes} onChangeText={setNotes} placeholder="Add a note for your future self..." placeholderTextColor={theme.colors.muted} multiline style={[styles.input, styles.notes]} /></View><View style={styles.share}><View style={styles.shareIcon}><Text style={{ color: theme.colors.coral, fontSize: 22 }}>♧</Text></View><View style={{ flex: 1 }}><Text style={styles.shareTitle}>Share with followers</Text><Text style={styles.shareCopy}>Keep private until you choose otherwise</Text></View><Switch value={share} onValueChange={setShare} trackColor={{ false: '#D2D4D0', true: theme.colors.coral }} /></View><Pressable onPress={save} style={[styles.saveButton, (!company || !role) && styles.saveDisabled]}><Text style={styles.saveText}>✓  Log {activityLabel[type].toLowerCase()}</Text></Pressable></ScrollView></KeyboardAvoidingView></Screen>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText?: (value: string) => void; placeholder?: string; editable?: boolean; keyboardType?: 'numeric' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} placeholderTextColor={theme.colors.muted} style={styles.input} /></View>; }
function InterviewDetails({ stage, setStage, outcome, setOutcome }: { stage: string; setStage: (value: string) => void; outcome: string; setOutcome: (value: string) => void }) { return <><Text style={styles.label}>INTERVIEW STAGE</Text><View style={styles.stageRow}>{['Phone screen', 'Technical', 'Onsite', 'Final'].map((item) => <Pressable key={item} onPress={() => setStage(item)} style={[styles.stage, stage === item && styles.stageActive]}><Text style={[styles.stageText, stage === item && styles.stageTextActive]}>{item}</Text></Pressable>)}</View><Text style={styles.label}>HOW DID IT GO?</Text><View style={styles.stageRow}>{['Great', 'Okay', 'Tough'].map((item) => <Pressable key={item} onPress={() => setOutcome(item)} style={[styles.stage, outcome === item && styles.stageActive]}><Text style={[styles.stageText, outcome === item && styles.stageTextActive]}>{item}</Text></Pressable>)}</View></>; }
const styles = StyleSheet.create({ content: { paddingBottom: 34 }, question: { marginHorizontal: 24, color: theme.colors.ink, fontSize: 25, marginBottom: 14 }, typeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginHorizontal: 24, marginBottom: 24 }, typeOption: { width: '31%', minHeight: 82, flexGrow: 1, backgroundColor: '#fff', borderColor: theme.colors.line, borderWidth: 1, borderRadius: 22, alignItems: 'center', justifyContent: 'center', padding: 8 }, typeOptionActive: { backgroundColor: theme.colors.coral, borderColor: theme.colors.coral }, typeIcon: { color: theme.colors.blue, fontSize: 23, marginBottom: 5 }, typeText: { color: theme.colors.muted, fontSize: 14, textAlign: 'center' }, typeTextActive: { color: '#fff' }, form: { backgroundColor: '#fff', borderColor: theme.colors.line, borderWidth: 1, borderRadius: 28, marginHorizontal: 24, padding: 16 }, formHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 }, formTitle: { color: theme.colors.ink, fontSize: 25 }, saved: { color: theme.colors.coral, backgroundColor: '#FFF0EC', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, fontWeight: '700' }, field: { marginBottom: 13 }, label: { color: theme.colors.muted, fontSize: 13, fontWeight: '800', marginBottom: 6, textTransform: 'uppercase' }, input: { backgroundColor: '#fff', borderWidth: 1, borderColor: theme.colors.line, color: theme.colors.ink, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 13, minHeight: 51, fontSize: 17 }, twoFields: { flexDirection: 'row', gap: 10 }, stageRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 16 }, stage: { paddingVertical: 8, paddingHorizontal: 11, borderRadius: 16, backgroundColor: theme.colors.input }, stageActive: { backgroundColor: theme.colors.blueSoft }, stageText: { color: theme.colors.muted, fontSize: 13 }, stageTextActive: { color: theme.colors.blue, fontWeight: '700' }, notes: { height: 92, textAlignVertical: 'top' }, share: { flexDirection: 'row', alignItems: 'center', gap: 12, marginHorizontal: 24, marginTop: 20, padding: 16, backgroundColor: '#FFF1ED', borderRadius: 24 }, shareIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: theme.colors.coralSoft, alignItems: 'center', justifyContent: 'center' }, shareTitle: { color: theme.colors.ink, fontSize: 17 }, shareCopy: { color: theme.colors.muted, fontSize: 14, marginTop: 2 }, saveButton: { backgroundColor: theme.colors.coral, borderRadius: 24, marginHorizontal: 24, alignItems: 'center', paddingVertical: 18, marginTop: 18 }, saveDisabled: { opacity: 0.55 }, saveText: { color: '#fff', fontSize: 21, fontWeight: '600' } });
