import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { ActivityCard, Heading, Screen } from '@/components/job-hunt-ui';
import { theme } from '@/constants/theme';
import { useJobHunt } from '@/data/job-hunt-store';

export default function FeedScreen() {
  const { activities } = useJobHunt();
  return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Heading eyebrow="Friday, October 2" title="Momentum" action="♧" /><View style={styles.goal}><View style={styles.ring}><Text style={styles.ringNumber}>72%</Text><Text style={styles.ringText}>weekly</Text></View><View style={{ flex: 1 }}><Text style={styles.streak}>♨  8 day streak</Text><Text style={styles.goalTitle}>Two more moves to hit your weekly goal.</Text><View style={styles.metrics}><Metric value="5" label="Applications" /><Metric value="2" label="Interviews" /><Metric value="3" label="Connections" /></View></View></View><View style={styles.feedTitle}><Text style={styles.sectionTitle}>Your network is moving</Text><Text style={styles.following}>Following</Text></View>{activities.filter((item) => item.visibility === 'friends').slice(0, 9).map((activity) => <ActivityCard key={activity.id} activity={activity} />)}</ScrollView></Screen>;
}
function Metric({ value, label }: { value: string; label: string }) { return <View><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 26 }, goal: { backgroundColor: theme.colors.navy, marginHorizontal: theme.spacing.xl, padding: theme.spacing.xl, borderRadius: 40, flexDirection: 'row', gap: 24, marginBottom: 24 }, ring: { width: 112, height: 112, borderRadius: 56, borderWidth: 13, borderColor: '#fff', alignItems: 'center', justifyContent: 'center' }, ringNumber: { color: '#fff', fontSize: 28, fontWeight: '800' }, ringText: { color: '#BEC9EB', fontSize: 16, fontWeight: '600' }, streak: { color: '#fff', fontSize: 17, marginBottom: 14 }, goalTitle: { color: '#fff', fontSize: 25, lineHeight: 30, letterSpacing: -0.4 }, metrics: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 }, metricValue: { color: '#fff', fontSize: 25, fontWeight: '800' }, metricLabel: { color: '#BEC9EB', fontSize: 13 }, feedTitle: { flexDirection: 'row', justifyContent: 'space-between', marginHorizontal: theme.spacing.xl, marginBottom: 16, alignItems: 'center' }, sectionTitle: { color: theme.colors.ink, fontSize: 25, letterSpacing: -0.5 }, following: { color: theme.colors.blue, fontSize: 17 } });
