import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Avatar, Chip, Heading, Screen } from '@/components/job-hunt-ui';
import { theme } from '@/constants/theme';
import { useJobHunt } from '@/data/job-hunt-store';

export default function SearchScreen() {
  const { users } = useJobHunt(); const [query, setQuery] = useState(''); const [kind, setKind] = useState('People'); const [following, setFollowing] = useState<string[]>([]);
  const results = useMemo(() => users.filter((user) => user.id !== 'alex' && `${user.name} ${user.headline} ${user.target_role}`.toLowerCase().includes(query.toLowerCase())), [query, users]);
  return <Screen><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Heading eyebrow="People & opportunities" title="Explore" action="☷" /><View style={styles.searchBox}><Text style={styles.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search people, jobs, or companies" placeholderTextColor={theme.colors.lightText} style={styles.searchInput} /></View><View style={styles.chips}><Chip label="People" selected={kind === 'People'} onPress={() => setKind('People')} /><Chip label="Jobs" selected={kind === 'Jobs'} onPress={() => setKind('Jobs')} /><Chip label="Companies" selected={kind === 'Companies'} onPress={() => setKind('Companies')} /></View>{query ? <><Text style={styles.resultsTitle}>{kind} results</Text>{kind === 'People' ? results.map((user) => <View key={user.id} style={styles.person}><Avatar user={user} /><View style={{ flex: 1 }}><Text style={styles.personName}>{user.name}</Text><Text style={styles.personMeta}>{user.headline} · {user.location}</Text></View><Pressable onPress={() => setFollowing((items) => items.includes(user.id) ? items.filter((item) => item !== user.id) : [...items, user.id])} style={[styles.followButton, following.includes(user.id) && styles.following]}><Text style={[styles.followText, following.includes(user.id) && styles.followingText]}>{following.includes(user.id) ? 'Following' : 'Follow'}</Text></Pressable></View>) : <OpportunityList kind={kind} query={query} />}</> : <><View style={styles.recentHeader}><Text style={styles.resultsTitle}>Recent searches</Text><Text style={styles.clear}>Clear</Text></View><View style={styles.recentChips}><Chip label="product designer" /><Chip label="remote" /><Chip label="Maya Chen" /></View><View style={styles.discover}><Text style={styles.discoverTitle}>Find your next connection</Text><Text style={styles.discoverCopy}>Search people, roles, or companies to see shared interview experiences.</Text></View></>}</ScrollView></Screen>;
}
function OpportunityList({ kind, query }: { kind: string; query: string }) { const names = kind === 'Companies' ? ['Linear', 'Meadow', 'Northstar Labs'] : ['Senior Product Designer', 'Product Designer', 'UX Researcher']; return <View>{names.map((name) => <View key={name} style={styles.opportunity}><View style={styles.companyMark}><Text style={{ color: theme.colors.coral, fontWeight: '800' }}>{name.charAt(0)}</Text></View><View><Text style={styles.personName}>{name}</Text><Text style={styles.personMeta}>{kind === 'Companies' ? '24 people in your network' : `Remote · Matches “${query}”`}</Text></View></View>)}</View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 28 }, searchBox: { marginHorizontal: theme.spacing.xl, backgroundColor: theme.colors.surface, borderColor: theme.colors.line, borderWidth: 1, borderRadius: 24, height: 76, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20 }, searchIcon: { fontSize: 31, color: theme.colors.muted, marginRight: 12 }, searchInput: { flex: 1, color: theme.colors.ink, fontSize: 19 }, chips: { flexDirection: 'row', gap: 10, marginHorizontal: theme.spacing.xl, marginTop: 24 }, resultsTitle: { marginHorizontal: theme.spacing.xl, color: theme.colors.ink, fontSize: 24, marginTop: 28, marginBottom: 14 }, recentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, clear: { color: theme.colors.coral, marginTop: 28, marginRight: theme.spacing.xl, fontSize: 16 }, recentChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginHorizontal: theme.spacing.xl }, person: { flexDirection: 'row', alignItems: 'center', gap: 12, marginHorizontal: theme.spacing.xl, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: theme.colors.line }, personName: { color: theme.colors.ink, fontSize: 18, fontWeight: '700' }, personMeta: { color: theme.colors.muted, fontSize: 14, marginTop: 4 }, followButton: { borderRadius: 18, backgroundColor: theme.colors.coral, paddingVertical: 9, paddingHorizontal: 13 }, following: { backgroundColor: theme.colors.coralSoft }, followText: { color: '#fff', fontWeight: '700', fontSize: 14 }, followingText: { color: theme.colors.coral }, discover: { margin: theme.spacing.xl, marginTop: 45, padding: 22, borderRadius: 24, backgroundColor: theme.colors.blueSoft }, discoverTitle: { color: theme.colors.navy, fontSize: 20, fontWeight: '700', marginBottom: 7 }, discoverCopy: { color: theme.colors.muted, fontSize: 15, lineHeight: 21 }, opportunity: { flexDirection: 'row', alignItems: 'center', gap: 14, marginHorizontal: theme.spacing.xl, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: theme.colors.line }, companyMark: { width: 48, height: 48, borderRadius: 14, backgroundColor: theme.colors.coralSoft, alignItems: 'center', justifyContent: 'center', fontSize: 20 } });
